set undofile
set undodir=~/.local/share/nvim/undodir
set foldmethod=syntax
set encoding=utf-8
set mouse=a
set laststatus=2
set showtabline=2
set tabstop=2
set expandtab
set shiftwidth=2
set cindent
set timeoutlen=1000
set ttimeoutlen=0
set hidden
set ignorecase
set smartcase
set pastetoggle=<F8>
"set autoindent
"set smartindent
"set nosmartindent
set cinkeys-=0#
set indentkeys-=0#
autocmd FileType * set cindent "some file types override it
